### ISSUE TITLE
Possible GSOC project: adding universal graph visualization via web (similar to Collective Mind but with AJAX)

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-analytics#6]
In Collective Mind, we had a universal plotter, where you could select any available dimension X,Y,Z and customize graph via web. We should add something similar to CK. Preliminary support is available via JSON:
http://cknowledge.org/repo/web.php?wcid=208c21b837924601:2d41f89bcf32d4d4:3b1b261d30f3934a

So we need to convert JSON into web selectors ...

**Comment by psyhtest** [comment]
Sounds like something we have implemented as part of [Quantum Collective Knowledge](http://cknowledge.org/quantum) :)

**Comment by gfursin** [comment]
You are right @psyhtest . I am closing this ticket!
